from typing import Protocol
from modules.quotation.quotation_type import QuotationNew, QuotationPatch, QuotationStatus, QuotationAcceptence

class IQuotationModule(Protocol):
    async def create_quotation(self, payload: QuotationNew) -> dict: ...
    async def patch_quotation(self, quote_id: int, payload: QuotationPatch) -> dict: ...
    async def delete_quotation(self, quote_id: int) -> dict: ...
    async def send_quotation(self, quote_id: int, payload: QuotationStatus) -> dict: ...
    async def record_response(self, quote_id: int, pyaload: QuotationAcceptence) -> dict: ...
    async def read_all_quotations(self) -> dict : ...
    async def read_quotation(self, quote_id: int): ...

