from typing import Protocol
from modules.inquiry.inquiry_types import InquiryNewNew, InquiryOldNew, InquiryOldOld, InquiryPatch, CommodityPatch, ContainerPatch

class IInquiryModule(Protocol):
    async def create_inquiry_case_1(self, payload: InquiryNewNew) -> dict: ...
    async def create_inquiry_case_2(self, payload: InquiryOldNew) -> dict: ...
    async def create_inquiry_case_3(self, payload: InquiryOldOld) -> dict: ...
    async def patch_inquiry_fields(self, inq_id: int, payload: InquiryPatch) -> dict: ...
    async def patch_commodity_fields(self, inq_id: int, com_id: int, payload: CommodityPatch) -> dict: ...
    async def patch_container_fields(self, inq_id: int, cont_id: int, payload: ContainerPatch) -> dict: ...
