from typing import Protocol
from modules.inquiry.inquiry_types import InquiryNewNew, InquiryOldNew, InquiryOldOld, InquiryPatch, InquiryView,CommodityPatch, ContainerPatch,RfqBulkNew, RfqPreviewResult

class IInquiryModule(Protocol):
    async def create_inquiry_case_1(self, payload: InquiryNewNew) -> dict: ...
    async def create_inquiry_case_2(self, payload: InquiryOldNew) -> dict: ...
    async def create_inquiry_case_3(self, payload: InquiryOldOld) -> dict: ...
    async def patch_inquiry_fields(self, inq_id: int, payload: InquiryPatch) -> dict: ...
    async def patch_commodity_fields(self, inq_id: int, com_id: int, payload: CommodityPatch) -> dict: ...
    async def patch_container_fields(self, inq_id: int, cont_id: int, payload: ContainerPatch) -> dict: ...
    async def read_inquiry(self, inq_id: int) -> list[dict]: ...
    async def read_all_inquiry(self) -> list[dict]: ...
    async def delete_inquiry(self, inq_id: int) -> dict: ...
    async def create_rfq_bulk(self, payload: RfqBulkNew) -> dict: ...
    async def preview_rfq_excel(self, file_bytes: bytes) -> RfqPreviewResult: ...