from typing import Protocol
from modules.client.client_types import ClientNew, ClientPatch, ContactPatch, KYCStatusPatch
from modules.inquiry.inquiry_types import ContactNew

class IClientModule(Protocol):
    async def create_new_client(self, payload: ClientNew) -> dict: ...
    async def patch_clients(self, cli_id: int, payload: ClientPatch) -> dict: ...
    async def patch_contact_person(self, cli_id: int, cpid: int, payload: ContactPatch) -> dict: ...
    async def add_contact_person(self, cli_id:int, payload:ContactNew)->dict: ...
    async def patch_kyc_status(self, cli_id:int, payload: KYCStatusPatch)->dict: ...
    async def read_all_clients(self)->list[dict]:...
    async def read_all_assigned_clients(self)-> list[dict]: ...
    async def fetch_all_contacts(self, cli_id: int)->list[dict]:...
    async def read_kyc_status(self, cli_id:int)-> dict : ...

