from typing import Protocol
from modules.client.client_types import ClientNew, ClientPatch, ContactPatch

class IClientModule(Protocol):
    async def create_new_client(self, payload: ClientNew) -> dict: ...
    async def patch_clients(self, cli_id: int, payload: ClientPatch) -> dict: ...
    async def patch_contact_person(self, cli_id: int, cpid: int, payload: ContactPatch) -> dict: ...
