from typing import Protocol
from modules.rates.rate_types import TarrifNew, TariffPatch, NACNew, NACPatch, ContractNew, ContractPatch

class IRatesMasterModule(Protocol):
    async def add_tariff_rate(self, payload: TarrifNew) -> dict: ...
    async def patch_tariff_rate(self, tar_id: int, payload: TariffPatch) -> dict: ...
    async def add_nac_rate(self, payload: NACNew) -> dict: ...
    async def patch_nac_rate(self, nac_id: int, payload: NACPatch) -> dict: ...
    async def add_contracted_rate(self, payload: ContractNew) -> dict: ...
    async def patch_contracted_rate(self, crate_id: int, payload: ContractPatch) -> dict: ...
    async def delete_tariff_rate(self, tar_id: int) -> dict: ...
    async def delete_nac_rate(self, nac_id: int) -> dict: ...
    async def delete_contracted_rate(self, crate_id: int) -> dict: ...
    async def read_nac_rate(self, nac_id: int) -> dict: ...
    async def read_all_nac_rates(self) -> list[dict]: ...
    async def read_client_nac_rates(self, cli_id:int) -> list[dict]:...
    async def read_contracted_rate(self, crate_id: int) -> dict: ...
    async def read_client_contracted_rates(self, cli_id:int) -> dict: ...
    async def read_all_contracted_rates(self) -> list[dict]: ...
    async def read_tariff_rate(self, tar_id: int) -> dict: ...
    async def read_all_tariff_rates(self) -> list[dict]: ...
