from typing import Protocol
from modules.rates.rates_master.rate_types import TarrifNew, TariffPatch, NACNew, NACPatch, ContractNew, ContractPatch

class IRatesMasterModule(Protocol):
    async def add_tariff_rate(self, payload: TarrifNew) -> dict: ...
    async def patch_tariff_rate(self, tar_id: int, payload: TariffPatch) -> dict: ...
    async def add_nac_rate(self, payload: NACNew) -> dict: ...
    async def patch_nac_rate(self, nac_id: int, payload: NACPatch) -> dict: ...
    async def add_contracted_rate(self, payload: ContractNew) -> dict: ...
    async def patch_contracted_rate(self, crate_id: int, payload: ContractPatch) -> dict: ...
