from typing import Protocol
from fastapi import UploadFile, File
from modules.booking.release_order.release_order_types import releaseOrderNew, releaseOrderPatch

class IReleaseOrderModule(Protocol):
    # TODO: returns extracted values to the frontend so the user could review
    async def upload_release_order(self, file: UploadFile=File(...)) -> dict: ...
    async def fetch_all_release_orders(self) -> dict: ...
    # TODO: MIGRATE THIS TO DOCUMENTATION MODULE
    # async def record_cutoffs(self, booking_id: int, payload: cutoffSchedules, file:UploadFile=File(...))-> dict:...
    async def create_realease_order(self, payload: releaseOrderNew) -> dict: ...
    async def patch_realease_order(self, ro_id: int, payload: releaseOrderPatch) -> dict: ...
