from typing import Protocol
from modules.inquiry.activity_log.activity_types import WorkflowStatusNew, WorkflowStatusPatch

class IAcitivityLog(Protocol):
    async def create_workflow(self, payload: WorkflowStatusNew) -> dict: ...
    async def update_workflow_status(self, inq_id: int, payload: WorkflowStatusPatch) -> dict: ...
    async def get_inquiry_status(self, inq_id: int) ->dict : ...