from typing import Protocol
from modules.rate_requests.rate_request_types import RateRequestNew, RateRequestOptionNew, RateRequestOptionPatch

class IRateRequestModule(Protocol):
    async def add_rate_request(self, payload: RateRequestNew) -> dict:
        ...
    async def delete_rate_request(self, request_id: int) -> dict:
        ...
    async def add_request_option(self, request_id: int, payload: RateRequestOptionNew) -> dict:
        ...
    async def delete_rate_request_option(self, request_id: int, option_id: int) -> dict:
        ...
    async def patch_rate_request_option(self, option_id: int, request_id: int, payload: RateRequestOptionPatch) -> dict:
        ...
    async def read_incoming_requests(self) -> list[dict]:
        ...