from typing import Protocol
from modules.rates.rate_types import VesselByVesselRateNew, VesselByVesselRatePatch, FAKRatesNew, FAKRatesPatch, SpecialRateNew, SpecialRatePatch

class IRatesModule(Protocol):
    async def add_vessel_rate(self, payload: VesselByVesselRateNew) -> dict: ...
    async def patch_vessel_rate(self, srid: int, payload: VesselByVesselRatePatch) -> dict: ...
    async def delete_vessel_rate(self, srid: int) -> dict: ...
    async def add_fak_rate(self, payload: FAKRatesNew) -> dict: ...
    async def patch_fak_rates(self, srid: int, payload: FAKRatesPatch) -> dict: ...
    async def delete_fak_rate(self, srid: int) -> dict: ...
    async def add_special_rate(self, payload: SpecialRateNew) -> dict: ...
    async def patch_special_rate(self, sprid: int, payload: SpecialRatePatch) -> dict: ...
    async def delete_special_rate(self, sprid: int) -> dict: ...
    async def read_all_fak_rates(self) -> list[dict]: ...
    async def read_all_vessel_rates(self) -> list[dict]: ...
    async def read_all_special_rates(self) -> list[dict]: ...
    async def read_non_persistent_rate(self, rate_id: int, rate_type: str) -> dict: ...
