from typing import Protocol
from modules.kyc.client_kyc_types import KYCRequestNew, KYCRequestPatch, DocumentChecklist, DocumentChecklistPatch, KYCStage

class IKYCModule(Protocol):
    async def create_kyc_request(self, cli_id:int, payload: KYCRequestNew) -> dict: ...
    async def patch_kyc_request(self, kyc_id: int, payload: KYCRequestPatch) -> dict: ...
    async def patch_document_checklist(self, doc_id: int, kyc_id: int, payload: DocumentChecklistPatch) -> dict: ...
    async def update_kyc_stage(self, cli_id: int, stage: KYCStage) -> dict: ...
