from modules.booking.booking_types import bookingRequestStatus, bookingRequestNew, bookingRequestPatch, bookingRequestReview
from typing import Protocol
from fastapi import UploadFile

class IBookingModule(Protocol):
    async def create_new_booking_req(self, emp_id_cs: int, payload: bookingRequestNew) -> dict : ...
    async def patch_booking_req(self, booking_id: int, updated_by: int, payload: bookingRequestPatch) -> dict : ...
    async def review_booking_req(self, booking_id: int, payload: bookingRequestReview) -> dict : ...
    async def confirm_booking_success(self, booking_id: int) -> dict: ... 
    async def upload_release_order() -> dict: ... 
    async def fetch_all_release_orders() -> dict: ... 
    # vgm_doc should be uploaded too
    # async def record_cutoffs(self, booking_id: int,  payload: )
    

    
